- name: test vmware
  hosts: all

  vars:
    vmware:
      host: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'

  tasks:
    - debug:
        vars: vmware
              username
              password
